// Constants & Seed Data for SDG Quest

export const LEVELS = [
  { level: 1, name: 'SDG Explorer', minXp: 0, icon: '🌱', planetStage: 'Seed', planetDesc: 'Your seed is planted in fresh soil!' },
  { level: 2, name: 'Earth Friend', minXp: 100, icon: '🌿', planetStage: 'Sprout', planetDesc: 'A tiny green sprout emerges into the sun!' },
  { level: 3, name: 'Change Maker', minXp: 300, icon: '🌳', planetStage: 'Tree', planetDesc: 'Your action tree blooms with leaves and fruit!' },
  { level: 4, name: 'Community Hero', minXp: 600, icon: '🌲', planetStage: 'Forest', planetDesc: 'A lush forest flourishes with wildlife and clean air!' },
  { level: 5, name: 'SDG Champion', minXp: 1000, icon: '🌎', planetStage: 'Thriving Planet', planetDesc: 'Your planet is radiant, sustainable, and full of life!' }
];

export const BADGES = [
  { id: 'water_saver', name: 'Water Saver', icon: '💧', category: 'SDG 6', desc: 'Turned off the tap while brushing teeth and saved precious water!', bg: 'bg-blue-100 text-blue-700 border-blue-300' },
  { id: 'nature_protector', name: 'Nature Protector', icon: '🌳', category: 'SDG 15', desc: 'Planted seeds or cared for local greenery!', bg: 'bg-emerald-100 text-emerald-700 border-emerald-300' },
  { id: 'waste_warrior', name: 'Waste Warrior', icon: '♻️', category: 'SDG 12', desc: 'Sorted recyclables and avoided single-use plastics!', bg: 'bg-amber-100 text-amber-700 border-amber-300' },
  { id: 'climate_explorer', name: 'Climate Explorer', icon: '🌎', category: 'SDG 13', desc: 'Learned about weather changes and turned off extra lights!', bg: 'bg-cyan-100 text-cyan-700 border-cyan-300' },
  { id: 'health_champion', name: 'Health Champion', icon: '❤️', category: 'SDG 3', desc: 'Ate a rainbow of veggies and stayed active for 30 mins!', bg: 'bg-rose-100 text-rose-700 border-rose-300' },
  { id: 'energy_detective', name: 'Energy Detective', icon: '⚡', category: 'SDG 7', desc: 'Discovered vampire energy electronics in the house!', bg: 'bg-yellow-100 text-yellow-700 border-yellow-300' },
  { id: 'food_hero', name: 'Food Hero', icon: '🍎', category: 'SDG 2', desc: 'Finished your plate and reduced food waste at dinner!', bg: 'bg-red-100 text-red-700 border-red-300' },
  { id: 'kindness_champion', name: 'Kindness Champion', icon: '🤝', category: 'SDG 10', desc: 'Shared toys and helped a friend at school!', bg: 'bg-purple-100 text-purple-700 border-purple-300' }
];

export const STICKERS = [
  { id: 'water_drop', name: 'Water Drop', icon: '💧' },
  { id: 'fish', name: 'Happy Fish', icon: '🐟' },
  { id: 'butterfly', name: 'Butterfly', icon: '🦋' },
  { id: 'recycle', name: 'Recycle', icon: '♻️' },
  { id: 'earth', name: 'Planet Earth', icon: '🌍' },
  { id: 'sun', name: 'Golden Sun', icon: '☀️' },
  { id: 'heart', name: 'Super Heart', icon: '❤️' },
  { id: 'star', name: 'Shining Star', icon: '⭐' },
  { id: 'sprout', name: 'Green Sprout', icon: '🌱' },
  { id: 'tree', name: 'Big Oak Tree', icon: '🌳' }
];

export const FRAMES = [
  { id: 'none', name: 'Clean Edge', border: 'border-2 border-slate-200' },
  { id: 'water', name: 'Ocean Ripple', border: 'border-8 border-cyan-400 bg-cyan-50 shadow-cyan-200' },
  { id: 'forest', name: 'Forest Leaves', border: 'border-8 border-emerald-500 bg-emerald-50 shadow-emerald-200' },
  { id: 'sun', name: 'Solar Shine', border: 'border-8 border-amber-400 bg-amber-50 shadow-amber-200' },
  { id: 'earth', name: 'Eco Globe', border: 'border-8 border-teal-500 bg-teal-50 shadow-teal-200' }
];

export const AVATAR_OPTIONS = {
  skin: ['#FFD1A4', '#E0A899', '#9F685B', '#5A3D31', '#FFDBAC'],
  hair: ['#2C1A1D', '#8D5B4C', '#D4A373', '#E63946', '#1E88E5', '#4CAF50'],
  style: ['Short Curly', 'Long Waves', 'Spiky', 'Ponytail', 'Cool Cap'],
  outfit: ['Eco Adventurer Tee', 'Water Guardian Hoodie', 'Solar Ranger Vest', 'Forest Scout Jacket'],
  accessories: ['Magnifying Glass 🔍', 'Binoculars 🔭', 'Water Bottle 🧴', 'Flower Crown 🌸', 'Eco Backpack 🎒']
};

export const SDGS_DATA = [
  {
    id: 1,
    number: 1,
    title: 'No Poverty',
    childTitle: 'Helping Everyone Thrive',
    color: '#E5243B',
    bgColor: 'bg-red-500',
    lightBg: 'bg-red-50',
    borderColor: 'border-red-300',
    icon: '🏠',
    description: 'Ensuring every child and family has shelter, clothes, and basic needs.',
    totalMissions: 4,
    completedMissions: 1,
    theme: { bgGradient: 'from-red-500 to-rose-600', pagePattern: '🏠 🤝 💛' },
    story: 'Imagine a big blanket that covers everyone in the community. When we share books, clothes, and warm smiles, we make sure nobody feels left out or cold!'
  },
  {
    id: 2,
    number: 2,
    title: 'Zero Hunger',
    childTitle: 'Delicious Food for All',
    color: '#DDA63A',
    bgColor: 'bg-amber-500',
    lightBg: 'bg-amber-50',
    borderColor: 'border-amber-300',
    icon: '🍎',
    description: 'Growing healthy food and making sure no tummy goes hungry.',
    totalMissions: 4,
    completedMissions: 2,
    theme: { bgGradient: 'from-amber-500 to-yellow-600', pagePattern: '🍎 🥦 🥕' },
    story: 'Plants grow from tiny seeds into yummy apples, crunchy carrots, and sweet berries! Eating good food gives us energy to play, run, and learn.'
  },
  {
    id: 3,
    number: 3,
    title: 'Good Health & Well-being',
    childTitle: 'Happy & Healthy Bodies',
    color: '#4C9F38',
    bgColor: 'bg-emerald-600',
    lightBg: 'bg-emerald-50',
    borderColor: 'border-emerald-300',
    icon: '❤️',
    description: 'Eating fresh veggies, getting strong through play, and resting well.',
    totalMissions: 5,
    completedMissions: 3,
    theme: { bgGradient: 'from-emerald-500 to-teal-600', pagePattern: '❤️ 🍎 🏃 🚴' },
    story: 'Your body is an amazing adventure machine! Drinking water, dancing to music, and laughing with friends keeps your heart super strong.'
  },
  {
    id: 4,
    number: 4,
    title: 'Quality Education',
    childTitle: 'Super Power of Learning',
    color: '#C5192D',
    bgColor: 'bg-rose-600',
    lightBg: 'bg-rose-50',
    borderColor: 'border-rose-300',
    icon: '📚',
    description: 'Opening books, asking curious questions, and discovering new things everyday.',
    totalMissions: 4,
    completedMissions: 2,
    theme: { bgGradient: 'from-rose-500 to-red-600', pagePattern: '📚 ✏️ 🎨 💡' },
    story: 'Every book is a magic portal to a new world. When we read and ask questions, our brains grow super muscle powers!'
  },
  {
    id: 5,
    number: 5,
    title: 'Gender Equality',
    childTitle: 'Equal Dreams for Everyone',
    color: '#FF3A21',
    bgColor: 'bg-orange-500',
    lightBg: 'bg-orange-50',
    borderColor: 'border-orange-300',
    icon: '⚖️',
    description: 'Girls and boys can be scientists, artists, astronauts, or whatever they dream!',
    totalMissions: 4,
    completedMissions: 1,
    theme: { bgGradient: 'from-orange-500 to-amber-600', pagePattern: '🚀 🎨 🔬 ⚽' },
    story: 'Whether building robot rockets or painting giant murals, boys and girls can do anything they set their minds to!'
  },
  {
    id: 6,
    number: 6,
    title: 'Clean Water & Sanitation',
    childTitle: 'Sparkling Clean Water',
    color: '#26BDE2',
    bgColor: 'bg-cyan-500',
    lightBg: 'bg-cyan-50',
    borderColor: 'border-cyan-300',
    icon: '💧',
    description: 'Protecting Earth’s precious water drops so humans, animals, and plants stay hydrated.',
    totalMissions: 5,
    completedMissions: 3,
    theme: { bgGradient: 'from-cyan-500 to-blue-600', pagePattern: '💧 🌊 🐟 🐬' },
    story: 'Water travels all around Earth — in clouds, rivers, oceans, and taps! Turning off the tap while brushing saves hundreds of drops every single day.'
  },
  {
    id: 7,
    number: 7,
    title: 'Affordable & Clean Energy',
    childTitle: 'Power from Sun & Wind',
    color: '#FCC30B',
    bgColor: 'bg-yellow-500',
    lightBg: 'bg-yellow-50',
    borderColor: 'border-yellow-300',
    icon: '⚡',
    description: 'Using sunlight, wind, and waves to power our lamps and toys cleanly.',
    totalMissions: 4,
    completedMissions: 2,
    theme: { bgGradient: 'from-yellow-400 to-amber-500', pagePattern: '☀️ 💨 ⚡ 🔋' },
    story: 'The sun sends free clean energy from 93 million miles away! Solar panels turn sunlight right into electricity for our computers and nightlights.'
  },
  {
    id: 8,
    number: 8,
    title: 'Decent Work & Economic Growth',
    childTitle: 'Creative Jobs & Fair Play',
    color: '#A21942',
    bgColor: 'bg-wine-600',
    lightBg: 'bg-pink-50',
    borderColor: 'border-pink-300',
    icon: '💼',
    description: 'Creating fun, safe, and helpful work where people are rewarded fairly.',
    totalMissions: 3,
    completedMissions: 1,
    theme: { bgGradient: 'from-pink-600 to-rose-700', pagePattern: '💼 🎨 🛠️ ⭐' },
    story: 'When people do jobs they love — like growing apples, teaching coding, or designing parks — the whole neighborhood prospers together!'
  },
  {
    id: 9,
    number: 9,
    title: 'Industry, Innovation & Infrastructure',
    childTitle: 'Clever Inventions & Bridges',
    color: '#FD6925',
    bgColor: 'bg-orange-600',
    lightBg: 'bg-orange-50',
    borderColor: 'border-orange-300',
    icon: '🏗️',
    description: 'Building eco-friendly trains, strong bridges, and smart inventions.',
    totalMissions: 4,
    completedMissions: 1,
    theme: { bgGradient: 'from-orange-500 to-red-500', pagePattern: '🤖 🏗️ 🌉 🚊' },
    story: 'Inventors use creativity to build solar-powered buses, recycled plastic roads, and windmills that make our cities super cool and clean.'
  },
  {
    id: 10,
    number: 10,
    title: 'Reduced Inequalities',
    childTitle: 'Welcoming Every Friend',
    color: '#DD1367',
    bgColor: 'bg-pink-600',
    lightBg: 'bg-pink-50',
    borderColor: 'border-pink-300',
    icon: '🤝',
    description: 'Treating all people with kindness, fairness, and inclusion.',
    totalMissions: 4,
    completedMissions: 2,
    theme: { bgGradient: 'from-pink-500 to-purple-600', pagePattern: '🤝 💛 🌈 🕊️' },
    story: 'Everyone brings a special color to our world rainbow. When we make sure playground ramps and games include everyone, playing becomes twice as fun!'
  },
  {
    id: 11,
    number: 11,
    title: 'Sustainable Cities & Communities',
    childTitle: 'Green & Happy Neighborhoods',
    color: '#FD9D24',
    bgColor: 'bg-amber-600',
    lightBg: 'bg-amber-50',
    borderColor: 'border-amber-300',
    icon: '🏡',
    description: 'Designing neighborhoods with parks, bike paths, and fresh clean air.',
    totalMissions: 4,
    completedMissions: 2,
    theme: { bgGradient: 'from-amber-500 to-orange-600', pagePattern: '🏡 🚲 🌳 🛝' },
    story: 'Imagine cities filled with rooftop flower gardens, quiet electric buses, and big sunny parks where birds sing and children play safely!'
  },
  {
    id: 12,
    number: 12,
    title: 'Responsible Consumption & Production',
    childTitle: 'Wise Use & Recycling',
    color: '#BF8B2E',
    bgColor: 'bg-yellow-600',
    lightBg: 'bg-yellow-50',
    borderColor: 'border-yellow-300',
    icon: '♻️',
    description: 'Using only what we need, recycling toys & paper, and reducing waste.',
    totalMissions: 5,
    completedMissions: 3,
    theme: { bgGradient: 'from-yellow-600 to-amber-700', pagePattern: '♻️ 📦 🛍️ 🌱' },
    story: 'Instead of throwing old things away, we can turn cardboard boxes into castle forts, compost apple cores into garden soil, and swap books with friends!'
  },
  {
    id: 13,
    number: 13,
    title: 'Climate Action',
    childTitle: 'Earth Guardian Adventure',
    color: '#3F7E44',
    bgColor: 'bg-green-700',
    lightBg: 'bg-green-50',
    borderColor: 'border-green-300',
    icon: '🌍',
    description: 'Planting trees, saving energy, and protecting Earth’s climate balance.',
    totalMissions: 5,
    completedMissions: 3,
    theme: { bgGradient: 'from-green-600 to-teal-700', pagePattern: '🌍 ☁️ 🌲 ☀️' },
    story: 'Earth is like our cozy home with an atmosphere blanket. When we plant trees and walk or bike instead of driving short trips, we keep Earth cool and happy!'
  },
  {
    id: 14,
    number: 14,
    title: 'Life Below Water',
    childTitle: 'Ocean Friends & Corals',
    color: '#0A97D9',
    bgColor: 'bg-sky-600',
    lightBg: 'bg-sky-50',
    borderColor: 'border-sky-300',
    icon: '🐙',
    description: 'Keeping seas clean for sea turtles, playful dolphins, and colorful fish.',
    totalMissions: 4,
    completedMissions: 2,
    theme: { bgGradient: 'from-sky-500 to-blue-700', pagePattern: '🐙 🐠 🦭 🪸' },
    story: 'Underneath the blue waves lives an enchanted kingdom of sea turtles, glowing jellyfish, and coral castles! Keeping trash off beaches protects ocean creatures.'
  },
  {
    id: 15,
    number: 15,
    title: 'Life on Land',
    childTitle: 'Forest & Wildlife Protectors',
    color: '#56C02B',
    bgColor: 'bg-emerald-500',
    lightBg: 'bg-emerald-50',
    borderColor: 'border-emerald-300',
    icon: '🌳',
    description: 'Protecting wild animals, green forests, soil bugs, and buzzing honeybees.',
    totalMissions: 5,
    completedMissions: 4,
    theme: { bgGradient: 'from-emerald-500 to-green-600', pagePattern: '🌳 🦋 🦊 🐾' },
    story: 'Forests are giant living homes for butterflies, squirrels, foxes, and birds. Every seed planted creates a new shelter and snack for woodland animals!'
  },
  {
    id: 16,
    number: 16,
    title: 'Peace, Justice & Strong Institutions',
    childTitle: 'Kindness, Peace & Fairness',
    color: '#00689D',
    bgColor: 'bg-blue-700',
    lightBg: 'bg-blue-50',
    borderColor: 'border-blue-300',
    icon: '🕊️',
    description: 'Solving arguments with peaceful words, sharing, and playing fair.',
    totalMissions: 4,
    completedMissions: 2,
    theme: { bgGradient: 'from-blue-600 to-indigo-700', pagePattern: '🕊️ ⚖️ 💙 🤝' },
    story: 'When friends disagree, taking a deep breath and listening helps us understand each other. Peace begins with a friendly smile and warm words!'
  },
  {
    id: 17,
    number: 17,
    title: 'Partnerships for the Goals',
    childTitle: 'Earth Teamwork Magic',
    color: '#19486A',
    bgColor: 'bg-indigo-900',
    lightBg: 'bg-indigo-50',
    borderColor: 'border-indigo-300',
    icon: '🌟',
    description: 'Working together across schools, families, and countries to save Earth!',
    totalMissions: 4,
    completedMissions: 3,
    theme: { bgGradient: 'from-indigo-700 to-slate-900', pagePattern: '🌟 🤝 🌎 🚀' },
    story: 'When many small hands join together, big wonderful things happen! Combining our ideas, kindness, and action makes us an unstoppable Earth Team!'
  }
];

export const INITIAL_MISSIONS = [
  {
    id: 'm_water_1',
    sdgId: 6,
    sdgNumber: 6,
    title: 'Become a Water Saver 💧',
    challengeText: 'Turn off the water tap while brushing your teeth for 3 full days!',
    bonusText: 'Find one more creative way your family can save water at home (e.g. collecting rainwater for plants).',
    xpReward: 50,
    badgeId: 'water_saver',
    badgeName: 'Water Saver',
    badgeIcon: '💧',
    submissionTypes: ['photo', 'drawing', 'text', 'checklist'],
    checklistItems: [
      'Turned off tap on Day 1 🦷',
      'Turned off tap on Day 2 🧼',
      'Turned off tap on Day 3 🌊',
      'Shared a water-saving tip with family 💬'
    ],
    status: 'active'
  },
  {
    id: 'm_land_1',
    sdgId: 15,
    sdgNumber: 15,
    title: 'Plant a Green Sprout 🌿',
    challengeText: 'Plant a seed in a small pot, cup, or garden and give it water & sunlight!',
    bonusText: 'Draw a picture of your seedling or write a friendly note to your plant.',
    xpReward: 60,
    badgeId: 'nature_protector',
    badgeName: 'Nature Protector',
    badgeIcon: '🌳',
    submissionTypes: ['photo', 'drawing', 'text'],
    checklistItems: [
      'Got a seed & soil 🪴',
      'Planted seed carefully 🌱',
      'Gave it a little water 💧',
      'Placed in sunny spot ☀️'
    ],
    status: 'available'
  },
  {
    id: 'm_consumption_1',
    sdgId: 12,
    sdgNumber: 12,
    title: 'Recycling Detective ♻️',
    challengeText: 'Inspect your home waste and sort 5 items into paper, plastic, or compost!',
    bonusText: 'Make a funny toy or fort out of an empty cardboard box.',
    xpReward: 50,
    badgeId: 'waste_warrior',
    badgeName: 'Waste Warrior',
    badgeIcon: '♻️',
    submissionTypes: ['photo', 'drawing', 'text', 'checklist'],
    checklistItems: [
      'Found paper or box 📦',
      'Found plastic bottle 🧴',
      'Found fruit peel for soil 🍏',
      'Sorted into bins properly 🗑️'
    ],
    status: 'available'
  },
  {
    id: 'm_climate_1',
    sdgId: 13,
    sdgNumber: 13,
    title: 'Energy Lights-Out Patrol ⚡',
    challengeText: 'Walk around your home and switch off lights in empty rooms before bedtime.',
    bonusText: 'Calculate how many lights your family turns off in 1 day!',
    xpReward: 40,
    badgeId: 'climate_explorer',
    badgeName: 'Climate Explorer',
    badgeIcon: '🌎',
    submissionTypes: ['photo', 'text', 'checklist'],
    checklistItems: [
      'Checked bedroom lights 🛏️',
      'Checked living room lights 🛋️',
      'Turned off unused lamps 💡',
      'Reminded family to save power ⚡'
    ],
    status: 'available'
  },
  {
    id: 'm_health_1',
    sdgId: 3,
    sdgNumber: 3,
    title: 'Rainbow Plate Challenge 🍎',
    challengeText: 'Eat 3 different colorful fruits or veggies in one day!',
    bonusText: 'Do 20 jumping jacks or dance to your favorite song for 5 minutes!',
    xpReward: 50,
    badgeId: 'health_champion',
    badgeName: 'Health Champion',
    badgeIcon: '❤️',
    submissionTypes: ['photo', 'drawing', 'text', 'checklist'],
    checklistItems: [
      'Ate something Green 🥦',
      'Ate something Red/Orange 🍎',
      'Ate something Yellow/Purple 🍌',
      'Drank a big glass of water 💧'
    ],
    status: 'available'
  }
];

export const INITIAL_BOOK_PAGES = [
  {
    id: 'page_1',
    sdgId: 6,
    sdgNumber: 6,
    title: 'My Water Saving Day 🌊',
    date: 'Sept 2026',
    caption: 'I turned off the tap while brushing my teeth for 3 days and saved 30 gallons of water!',
    type: 'photo',
    mediaUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b7?auto=format&fit=crop&w=600&q=80',
    frame: 'water',
    stickers: ['💧', '🐟', '⭐'],
    xpEarned: 50,
    badgeName: 'Water Saver',
    badgeIcon: '💧',
    author: 'Leo'
  },
  {
    id: 'page_2',
    sdgId: 15,
    sdgNumber: 15,
    title: 'Little Sunflower Sprout 🌿',
    date: 'Sept 2026',
    caption: 'My sunflower seed pushed open the soil today! I named him Sunny.',
    type: 'drawing',
    mediaUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=600&q=80',
    frame: 'forest',
    stickers: ['🌱', '🦋', '☀️'],
    xpEarned: 60,
    badgeName: 'Nature Protector',
    badgeIcon: '🌳',
    author: 'Leo'
  },
  {
    id: 'page_3',
    sdgId: 12,
    sdgNumber: 12,
    title: 'Cardboard Robot Fort ♻️',
    date: 'Sept 2026',
    caption: 'Instead of throwing away the cereal boxes, I built a recycled space robot!',
    type: 'photo',
    mediaUrl: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?auto=format&fit=crop&w=600&q=80',
    frame: 'sun',
    stickers: ['♻️', '📦', '⭐'],
    xpEarned: 50,
    badgeName: 'Waste Warrior',
    badgeIcon: '♻️',
    author: 'Leo'
  }
];
